<?php

namespace Grupanel\BackendBundle\Controller;

use Grupanel\BackendBundle\Form\FileType;
use Grupanel\CoreBundle\Entity\File;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/file")
 */
class FileUploadController extends Controller
{
    /**
     * @Route("/", name="file_upload")
     * @Template()
     */
    public function indexAction(Request $request)
    {
		$entityFile = new File();
		$form = $this->createForm(new FileType(), $entityFile);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			// $file stores the uploaded PDF file
			/** @var Symfony\Component\HttpFoundation\File\UploadedFile $file */
			$file = $entityFile->getName();

			$fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

			// moves the file to the directory where brochures are stored
			if ($file->move(
				$this->getParameter('media_directory'),
				$fileName
			)) {
				$entityFile->setName($fileName);

				$entityManager = $this->getDoctrine()->getManager();
				$fileType = $entityManager->find(File::class, 1);

				$entityFile->setFileType($fileType);
				$entityFile->setExtension('xxx');

				$entityManager->persist();
				$entityManager->flush();
			}else{
				$this->get('session')->getFlashBag()->add(
					'error',
					'Erro!'
				);
			}

			return $this->redirect($this->generateUrl('file_upload'));
		}

		return $this->render('@Backend/FileUpload/index.html.twig', array(
			'form' => $form->createView(),
		));
    }

	/**
	 * @return string
	 */
	private function generateUniqueFileName()
	{
		// md5() reduces the similarity of the file names generated by
		// uniqid(), which is based on timestamps
		return md5(uniqid());
	}

}
