parameters:
        grupanel.doctrine_listener.class: Grupanel\BackendBundle\Listener\DoctrineListener

services:
    doctrine_global_listener:
        class: %grupanel.doctrine_listener.class%
        tags:
            - { name: doctrine.event_listener, event:preUpdate}
            - { name: doctrine.event_listener, event:postUpdate}
            - { name: doctrine.event_listener, event:postPersist}
            - { name: doctrine.event_listener, event:preRemove}
            - { name: doctrine.event_listener, event:postFlush}
        arguments:    [@service_container]

    grupanel.balance:
        class: Grupanel\BackendBundle\Services\BalanceManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @service_container

    grupanel.storage:
        class: Grupanel\BackendBundle\Services\StorageManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - @service_container
    grupanel.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory: ['Grupanel\BackendBundle\Menu\Builder', createBreadcrumbMenu] # the menu builder service above
        arguments: ["@request"]
        scope: request
        tags:
        - { name: knp_menu.menu, alias: breadcrumb } # The alias is used in the template

